routes/admin.php
<?php

/** mega admin routes **/

Route::get('/', 'DashboardController@index')->name('home');
Route::resource('/team', 'TeamController');
Route::get('/video', 'VideoController@index')->name('video.index');
Route::post('/video','VideoController@store')->name('video.store');
Route::resource('/contact', 'ContactController');
Route::resource('/referal', 'ReferalController');
Route::resource('/tasks', 'TasksController');
Route::post('/tasks/activate/{id}', 'TasksController@activate')->name('tasks.activate');
Route::resource('/reviews', 'ReviewsController');
Route::get('/users','UsersController@index')->name('users.index');
Route::get('/users/{id}','UsersController@tasks')->name('users.tasks');
Route::get('/users/{id}/payments', 'UsersController@payments')->name('users.payments');
Route::get('/users/{id}/task/{task_id}','UsersController@task')->name('users.task');
Route::post('/users/{id}/task/{task_id}','UsersController@task_update')->name('users.task_update');
Route::resource('/schedule', 'ScheduleController');
Route::resource('/withdraws', 'WithdrawController');
Route::resource('/online', 'OnlineController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login')->name('login_post');
Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
Route::post('/register', 'Auth\RegisterController@register')->name('register');
Route::match(['GET', 'POST'], '/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/agreement', 'LandingsController@agreement')->name('agreement');
Route::get('/politics', 'LandingsController@politics')->name('politics');
Route::get('/otkaz', 'LandingsController@otkaz')->name('otkaz');

Route::group([
    'middleware' => ['marks']
], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/online', 'HomeController@trening')->name('trening');
    Route::get('/webinar','HomeController@webinar')->name('webinar');
    Route::post('/webinar','HomeController@webinar_post')->name('webinar.post');
	
    Route::get('/webinar1','HomeController@webinar1')->name('webinar1');
    Route::get('/webinar2','HomeController@webinar2')->name('webinar2');
    Route::post('/webinar1','HomeController@webinar_post')->name('webinar1.post');
	
    Route::get('/thanks','HomeController@webinar_oto')->name('webinar.oto');
    Route::post('/thanks','HomeController@webinar_oto_post')->name('webinar.oto_post');
    Route::post('/thanks','HomeController@webinar_oto_post')->name('webinar.oto_post');
    Route::post('/webinar/register','HomeController@webinar_register')->name('webinar.register');
    Route::get('/webinar/sale','HomeController@webinar_sale')->name('webinar.sale');
    Route::post('/webinar/sale','HomeController@webinar_sale_reg')->name('webinar.sale_reg');
    Route::post('/club_register','HomeController@club_register')->name('club_register');
    Route::get('/fitness', 'HomeController@fitness')->name('fitness');
    Route::get('/fitness/{link}', 'ReferalController@fitness')->name('fitness_ref');
    Route::get('/checkout/{id}', 'HomeController@checkout')->name('checkout');
    Route::get('/trening/{link}', 'ReferalController@trening')->name('trening_ref');

    Route::get('coaching', 'LandingsController@coaching')->name('coaching.index');
    Route::get('coaching/register', 'LandingsController@coaching_reg_show')->name('coaching.reg_show');
    Route::post('coaching/register', 'LandingsController@coaching_register')->name('coaching.register');

    Route::get('/av-2/sale','HomeController@av2_sale');
    Route::post('/av-2/sale','HomeController@av2_sale_reg')->name('av2_sale');

    Route::get('/av-3/sale', 'LandingsController@av3_sale');
    Route::post('/av-3/sale', 'LandingsController@av3_sale_reg')->name('av3_sale');
    Route::get('/av-4/sale', 'LandingsController@av4_sale');
    Route::post('/av-4/sale', 'LandingsController@av4_sale_reg')->name('av4_sale');

});

Route::get('/test/{id}', 'TestController@index');

//for founds
Route::get('/payment', 'PaymentsController@get')->name('payment.index');
Route::post('/payment', 'PaymentsController@post')->name('payment.check');
Route::get('/payment/fail', 'PaymentsController@fail')->name('payment.fail');
Route::get('/payment/ok', 'PaymentsController@ok')->name('payment.ok');
Route::get('/payment/wait', 'PaymentsController@wait')->name('payment.wait');

app/Http/Controllers/Admin/ScheduleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\GameSchedule;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Carbon;

class ScheduleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $schedules = GameSchedule::getLast();
        return view('admin.schedule.index',compact('schedules'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.schedule.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store (Request $request)
    {
        $post = $request->except('_token');

        $post['date'] = Carbon::parse($request->date);

        GameSchedule::create( $post );

        return redirect()->route('admin.schedule.index')
            ->with('success','Успешно добавлено');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $schedule = GameSchedule::find($id)->toArray();
        $schedule['date'] = Carbon::parse($schedule['date'])->timestamp * 1000;
        return view('admin.schedule.edit', compact('schedule'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $schedule = GameSchedule::find($id);
        $schedule->date = Carbon::parse($request->date);
        $schedule->title = $request->title;
        $schedule->host = $request->host;
        $schedule->text = $request->text;
        $schedule->save();
        return redirect()->route('admin.schedule.index')
            ->with('success','Успешно изменен');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        GameSchedule::find($id)->delete();
        return redirect()->route('admin.schedule.index')
            ->with('success','Успешно удален');
    }
}

resources/views/admin/schedule/create.blade.php
@extends('admin.layouts.app')
@section('title', "Добавление расписания")
@section('description', "Добавление расписания" )
@section('content')
    <h1>Добавление расписания</h1>

    <section>
        <div class="section_item w70">
            <div class="section_item_wrap">
                <form method="POST" enctype="multipart/form-data" action="{{ route('admin.schedule.store') }}">
                    @csrf
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control datepicker-here"
                               name="date"
                               autocomplete="off"
                               value="{{ old('date') }}" required placeholder="Время вебинара">

                        @error('date')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="title"
                               autocomplete="off"
                               value="{{ old('title') }}"  placeholder="Заголовок">

                        @error('title')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="host"
                               autocomplete="off"
                               value="{{ old('host') }}"  placeholder="Спикер">

                        @error('host')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <textarea required name="text" id="" cols="30" rows="10" placeholder="Текст задания">{{ old('text') }}</textarea>
                        @error('text')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <button type="submit" class="button"><i class="fas fa-sign-in-alt"></i> Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @if(session('success'))
        <script>swal({icon:'success',title:'{{ session('success') }}'});</script>
    @endif
    @include('datapicker')
    @push('js')
        <script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
        <script>
            CKEDITOR.replace( 'text' );
        </script>
    @endpush
@endsection

resources/views/admin/schedule/edit.blade.php
@extends('admin.layouts.app')
@section('title', "Добавление задания")
@section('description', "Добавление задания" )
@section('content')
    <h1>Добавление задания</h1>

    <section>
        <div class="section_item w50">
            <div class="section_item_wrap">
                <form method="POST" enctype="multipart/form-data" action="{{ route('admin.schedule.update', $schedule['id'] ) }}">
                    @csrf
                    @method('PUT')
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control datepicker-here"
                               name="date"
                               data-time="{{ $schedule['date'] }}"
                               value="" required placeholder="Время вебинара">

                        @error('date')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="title"
                               value="{{ $schedule['title'] }}"  placeholder="Заголовок">

                        @error('title')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="host"
                               value="{{ $schedule['host'] }}"  placeholder="Спикер">

                        @error('host')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <textarea required name="text" id="" cols="30" rows="10" placeholder="Текст задания">{{ $schedule['text'] }}</textarea>
                        @error('text')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <button type="submit" class="button"><i class="fas fa-sign-in-alt"></i> Изменить</button>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @if(session('success'))
        <script>swal({icon:'success',title:'{{ session('success') }}'});</script>
    @endif
    @include('datapicker')
    @push('js')
        <script src="https://cdn.ckeditor.com/4.11.4/standard/ckeditor.js"></script>
        <script>
            CKEDITOR.replace( 'text' );
        </script>
    @endpush
@endsection

resources/views/admin/schedule/index.blade.php
@extends('admin.layouts.app')
@section('title', "Расписание")
@section('description', "Расписание" )
@section('content')
    <h1>Расписание</h1>
    <a href="{{ route('admin.schedule.create') }}" class="button"><i class="fas fa-user-plus"></i> Добавить</a>
    <section style="margin-top: 30px;">
        @foreach($schedules as $schedule)
            <div class="section_item">
                <div class="section_item_wrap">
                    <div class="section_with_button">
                        <h4>{{ Carbon::parse($schedule->date)->format('H:i d.m.Y') }}</h4>
                        <div class="section_with_button--buttons">
                            <a href="{{ route('admin.schedule.edit', $schedule->id) }}" class="button">
                                <i class="fas fa-external-link-square-alt"></i> Изменить
                            </a>
                            <form action="{{ route('admin.schedule.destroy', $schedule->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <div class="auth_form_group">
                                    <button type="submit" class="button"><i class="fas fa-sign-in-alt"></i> Удалить</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
    </section>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @if(session('success'))
        <script>swal({icon:'success',title:'{{ session('success') }}'});</script>
    @endif
@endsection