routes/admin.php
<?php

/** mega admin routes **/

Route::get('/', 'DashboardController@index')->name('home');
Route::resource('/team', 'TeamController');
Route::get('/video', 'VideoController@index')->name('video.index');
Route::post('/video','VideoController@store')->name('video.store');
Route::resource('/contact', 'ContactController');
Route::resource('/referal', 'ReferalController');
Route::resource('/tasks', 'TasksController');
Route::post('/tasks/activate/{id}', 'TasksController@activate')->name('tasks.activate');
Route::resource('/reviews', 'ReviewsController');
Route::get('/users','UsersController@index')->name('users.index');
Route::get('/users/{id}','UsersController@tasks')->name('users.tasks');
Route::get('/users/{id}/payments', 'UsersController@payments')->name('users.payments');
Route::get('/users/{id}/task/{task_id}','UsersController@task')->name('users.task');
Route::post('/users/{id}/task/{task_id}','UsersController@task_update')->name('users.task_update');
Route::resource('/schedule', 'ScheduleController');
Route::resource('/withdraws', 'WithdrawController');
Route::resource('/online', 'OnlineController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Auth::routes();

Route::get('/login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('/login', 'Auth\LoginController@login')->name('login_post');
Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
Route::post('/register', 'Auth\RegisterController@register')->name('register');
Route::match(['GET', 'POST'], '/logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/agreement', 'LandingsController@agreement')->name('agreement');
Route::get('/politics', 'LandingsController@politics')->name('politics');
Route::get('/otkaz', 'LandingsController@otkaz')->name('otkaz');

Route::group([
    'middleware' => ['marks']
], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('/online', 'HomeController@trening')->name('trening');
    Route::get('/webinar','HomeController@webinar')->name('webinar');
    Route::post('/webinar','HomeController@webinar_post')->name('webinar.post');
	
    Route::get('/webinar1','HomeController@webinar1')->name('webinar1');
    Route::get('/webinar2','HomeController@webinar2')->name('webinar2');
    Route::post('/webinar1','HomeController@webinar_post')->name('webinar1.post');
	
    Route::get('/thanks','HomeController@webinar_oto')->name('webinar.oto');
    Route::post('/thanks','HomeController@webinar_oto_post')->name('webinar.oto_post');
    Route::post('/thanks','HomeController@webinar_oto_post')->name('webinar.oto_post');
    Route::post('/webinar/register','HomeController@webinar_register')->name('webinar.register');
    Route::get('/webinar/sale','HomeController@webinar_sale')->name('webinar.sale');
    Route::post('/webinar/sale','HomeController@webinar_sale_reg')->name('webinar.sale_reg');
    Route::post('/club_register','HomeController@club_register')->name('club_register');
    Route::get('/fitness', 'HomeController@fitness')->name('fitness');
    Route::get('/fitness/{link}', 'ReferalController@fitness')->name('fitness_ref');
    Route::get('/checkout/{id}', 'HomeController@checkout')->name('checkout');
    Route::get('/trening/{link}', 'ReferalController@trening')->name('trening_ref');

    Route::get('coaching', 'LandingsController@coaching')->name('coaching.index');
    Route::get('coaching/register', 'LandingsController@coaching_reg_show')->name('coaching.reg_show');
    Route::post('coaching/register', 'LandingsController@coaching_register')->name('coaching.register');

    Route::get('/av-2/sale','HomeController@av2_sale');
    Route::post('/av-2/sale','HomeController@av2_sale_reg')->name('av2_sale');

    Route::get('/av-3/sale', 'LandingsController@av3_sale');
    Route::post('/av-3/sale', 'LandingsController@av3_sale_reg')->name('av3_sale');
    Route::get('/av-4/sale', 'LandingsController@av4_sale');
    Route::post('/av-4/sale', 'LandingsController@av4_sale_reg')->name('av4_sale');

});

Route::get('/test/{id}', 'TestController@index');

//for founds
Route::get('/payment', 'PaymentsController@get')->name('payment.index');
Route::post('/payment', 'PaymentsController@post')->name('payment.check');
Route::get('/payment/fail', 'PaymentsController@fail')->name('payment.fail');
Route::get('/payment/ok', 'PaymentsController@ok')->name('payment.ok');
Route::get('/payment/wait', 'PaymentsController@wait')->name('payment.wait');

app/Http/Controllers/Admin/TeamController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\TeamAdd;
use App\Http\Traits\StoreImg;
use App\Model\Team;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TeamController extends Controller
{
    use StoreImg;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = Team::all();
        return view('admin.team.index', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.team.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TeamAdd $request)
    {
        $teacher = new Team();
        $teacher->name = $request->name;
        $teacher->position = $request->position;
        $teacher->description = $request->description;
        $teacher->img = $request->hasFile('img')
            ? $this->storeImg($request,'team','img')
            : 'img/no-avatar.jpg';
        $teacher->save();
        return redirect()->route('admin.team.index')
            ->with([
                'success' => 'Член команды был добавлен'
            ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $teacher = Team::where('id',$id)->first();
        return view('admin.team.edit', compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TeamAdd $request, $id)
    {
        $teacher = Team::where('id',$id)->first();
        $teacher->name = $request->name;
        $teacher->name = $request->name;
        $teacher->position = $request->position;
        $teacher->description = $request->description;
        if($request->hasFile('img')) {
            $teacher->img = $this->storeImg($request,'team','img');
        }
        $teacher->save();
        return redirect()->route('admin.team.index')->with([
            'success' => 'Член команды был обновлен'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Team::destroy($id);
        return redirect()->route('admin.team.index')->with([
            'success' => 'Член комманды удален'
        ]);
    }
}

app/Http/Controllers/Cabinet/TeamController.php
<?php

namespace App\Http\Controllers\Cabinet;

use App\Model\Team;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class TeamController extends Controller
{
    public function index() {
        $teachers = Team::all();
        return view('cabinet.team', compact('teachers'));
    }
}

resources/views/admin/team/create.blade.php
@extends('admin.layouts.app')
@section('title', "Добавление в команду")
@section('description', "Добавление в команду" )
@section('content')
    <h1>Добавление в команду</h1>
    <section>
        <div class="section_item w50">
            <div class="section_item_wrap">
                <div class="section_img js-avatar" style="background-image: url({{ asset($user->info->img ?? 'img/no-avatar.jpg') }})"></div>
                <form method="POST" enctype="multipart/form-data" action="{{ route('admin.team.store') }}">
                    @csrf
                    <input type="file" accept="image/*" name="img" id="avatar">
                    <label for="avatar"><i class="fas fa-cloud-download-alt"></i> Выбрать аватар</label>

                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="name"
                               value="{{ old('name') }}" required placeholder="Имя">

                        @error('name')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="position"
                               value="{{ old('position') }}" required placeholder="Должность">

                        @error('position')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="description"
                               value="{{ old('description') }}" required placeholder="Описание">

                        @error('description')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <button type="submit" class="button"><i class="fas fa-sign-in-alt"></i> Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    @push('js')
        <script>
            $('#avatar').on('change', function(e) {
                var file = $(this).prop('files')[0];
                getBase64(file).then(function(imgBase64) {
                    $('.js-avatar').attr('style','background-image: url('+imgBase64+')');
                });
            });

            function getBase64(file) {
                return new Promise((res,rej) => {
                    var reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = function () {
                        res(reader.result)
                    };
                    reader.onerror = function (error) {
                        rej(error);
                    };
                });
            }
        </script>

    @endpush
@endsection

resources/views/admin/team/edit.blade.php
@extends('admin.layouts.app')
@section('title', "Добавление в команду")
@section('description', "Добавление в команду" )
@section('content')
    <h1>Изменить {{ $teacher->name }}</h1>
    <section>
        <div class="section_item w50">
            <div class="section_item_wrap">
                <div class="section_img js-avatar" style="background-image: url({{ asset($teacher->img ?? 'img/no-avatar.jpg') }})"></div>
                <form method="POST" enctype="multipart/form-data" action="{{ route('admin.team.update', $teacher->id) }}">
                    @csrf
                    @method('PUT')
                    <input type="file" accept="image/*" name="img" id="avatar">
                    <label for="avatar"><i class="fas fa-cloud-download-alt"></i> Выбрать аватар</label>

                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="name"
                               value="{{ old('name') ?? $teacher->name }}" required placeholder="Имя">

                        @error('name')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="position"
                               value="{{ old('position') ?? $teacher->position }}" required placeholder="Должность">

                        @error('position')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <input type="text"
                               class="form-control"
                               name="description"
                               value="{{ old('description') ?? $teacher->description }}" required placeholder="Описание">

                        @error('description')
                        <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="auth_form_group">
                        <button type="submit" class="button"><i class="fas fa-sign-in-alt"></i> Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </section>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @error('img')
    <script>swal({icon:'error',title:'{{ $message }}'})</script>
    @enderror
    @push('js')
        <script>
            $('#avatar').on('change', function(e) {
                var file = $(this).prop('files')[0];
                getBase64(file).then(function(imgBase64) {
                    $('.js-avatar').attr('style','background-image: url('+imgBase64+')');
                });
            });

            function getBase64(file) {
                return new Promise((res,rej) => {
                    var reader = new FileReader();
                    reader.readAsDataURL(file);
                    reader.onload = function () {
                        res(reader.result)
                    };
                    reader.onerror = function (error) {
                        rej(error);
                    };
                });
            }
        </script>

    @endpush
@endsection

resources/views/admin/team/index.blade.php
@extends('admin.layouts.app')
@section('title', "Команда")
@section('description', "Команда" )
@section('content')
    <h1>Команда</h1>
    <a href="{{ route('admin.team.create') }}" class="button"><i class="fas fa-user-plus"></i> Добавить</a>
    <section  style="margin-top:30px">
        @foreach($teachers as $teacher)
        <div class="section_item">
            <div class="section_item_wrap">
                <div class="team_wrapper">
                    <div class="team_item">
                        <div class="team_item_img" style="background-image: url('{{ asset($teacher->img) }}')"></div>
                        <div class="team_item_descr">
                            <p class="title">{{ $teacher->name }}</p>
                            <p class="subtext">{{ $teacher->position }}</p>
                            <p class="subtext">{{ $teacher->description }}</p>
                            <a style="margin-top: 10px;" href="{{route('admin.team.edit', $teacher->id)}}" class="button">Изменить</a>
                            <form style="display: inline-block;" action="{{ route('admin.team.destroy',$teacher->id) }}" method="POST">
                                @csrf
                                @method("DELETE")
                                <button class="button" type="submit">Удалить</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @endforeach
    </section>

    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @if(session('success'))
        <script>swal({icon:'success',title:'{{ session('success') }}'});</script>
    @endif
@endsection